### ISSUE TITLE
Getting started and Choosing the right hardware

### ISSUE THREAD

**Issue by danededane** [gjkrediet/Fluid-controller#1]
Hi @gjkrediet , 

I want to try to recreate your controller so before I order everything I hoped you would take a look and verify that its the right components I've found. I dont know how long the aliexpress links works so i've added some images just in case someone else sees this.

- **LilyGO TTGO T-Display V1.1 which is a developmentboard with an ESP32, with a built-in tft (IPS) display and battery-charger. I purchased it for about €13 from internet.**
![image](https://github.com/gjkrediet/Fluid-controller/assets/9024493/18d2d871-ab2c-4d73-aec2-bec38dfbaf6f)
[link](https://www.aliexpress.com/item/1005003745502352.html?spm=a2g0o.cart.0.0.202b38daKSeNMR&mp=1)

- **Rotary encoder / dial (about €1)**
![image](https://github.com/gjkrediet/Fluid-controller/assets/9024493/74e3f445-cc87-459c-8553-4892db70ee9d)
[link](https://www.aliexpress.com/item/1005005973850924.html?spm=a2g0o.cart.0.0.202b38daKSeNMR&mp=1)
 
- **Three simple colored buttons NO (total of €2)**
![image](https://github.com/gjkrediet/Fluid-controller/assets/9024493/fed40319-d90a-4205-a439-ffc645baba88)
[link](https://www.aliexpress.com/item/1005005904666959.html?spm=a2g0o.order_list.order_list_main.11.49011802j2I8of)
 
- **PSP joystick (about €3)**
![image](https://github.com/gjkrediet/Fluid-controller/assets/9024493/4cddcc2d-cc4f-42e3-9763-04d856f2a348)
[link](https://www.aliexpress.com/item/1005005985509291.html?spm=a2g0o.cart.0.0.202b38daKSeNMR&mp=1)

- **Pin bases for the pcb**
![image](https://github.com/gjkrediet/Fluid-controller/assets/9024493/3ee6b01f-ce76-4241-9474-a46e8c9e581b)
[link](https://www.aliexpress.com/item/1005006043456317.html?spm=a2g0o.cart.0.0.202b38daKSeNMR&mp=1)
 
- **Single-sided pcb**
I just uploaded the file to pcbway. Are the defaults alright? 
sorry if I seem a little stupid. I've never tried ordering a pcb before 😄 

![image](https://github.com/gjkrediet/Fluid-controller/assets/9024493/8cf870da-061d-4d1c-b4f3-19cc5cb04538)

I have 18650 laying around and tons of filament. 
Anything else? It's just so annoying ordering everything, waiting 6 weeks and realizing you forgot something.

One more thing. Maybe before I order we could change the pcb so there's room for the joystick 😉

**Comment by gjkrediet** [comment]
Hi @cvjensen. For the most part your list looks allright. The rotary encoder should be one that can be soldered on the pcb like this: 
![afbeelding](https://github.com/gjkrediet/Fluid-controller/assets/20277013/4e175536-a99a-4f23-a93b-5ed0c5e526db)
The 'pin bases' from your picture are what I call, female pcb-headers. You are correct that these should be soldered on the pcb. You should also have some M3 screws and some wires of which 5 have 'dupont' connectors. You could perhaps best use pre-made wires with dupont-connectors like these:
![afbeelding](https://github.com/gjkrediet/Fluid-controller/assets/20277013/7f4d64ef-7248-4ec0-a110-a1557004ae62)
I always keep my pcb's simple and make them myself. I isolation-routed the connections on a single-sided PCB. I can imagine there is a learning-curve there, so maybe its easier to outsource it. I have no experience whatsoever whith that. So you are on your own there. Sorry.
I will take a look at the pcb-design though next week, also because I realised that the diameter of the various holes in the design might not be correct. So please have some patience with that.

**Comment by danededane** [comment]
Thanks for the answer. I've now changed the encoder. And sorry I forgot to mention that I have dupont cables and M3's 😄 

Then I guess I can order all the hardware right away and then I can order the PCB next week if you get the time to make the changes .

If you want to you could update the readme with pictures of the hardware. 
I guess it would make it a little easier for the next one that wants to replicate it.

**Comment by gjkrediet** [comment]
@cvjensen thanks for your tips. I have updated the edge-cuts of the PCB. The size of the holes seems to be OK. The pads are quite large (to best facilitate edge-routing). Please let me know if this works out OK in the end-result.

**Comment by danededane** [comment]
@gjkrediet I dont see any recent changes in the files. Remembered to git commit and git upload?

**Comment by gjkrediet** [comment]
@cvjensen you are right. There's a bit of a learning curve with Github. Committed it just now.

**Comment by danededane** [comment]
@gjkrediet thanks - I'll test it out in about a month when everything arrives 😄

**Comment by danededane** [comment]
@gjkrediet apparently I need a gerber file to order from pcbway. I'm getting this error:

The file can not be opened, please upload Gerber files in format of RS-274x.;

Anything you are familiar with?

**Comment by gjkrediet** [comment]
@cvjensen In Kicad you can create gerber-files. If you don't have Kicad you can download it for free. To create a gerber-file you can ignore all the possibilities of Kicad. Just load the PCB-file in Kicad and select pcb-editor->file->plot. 
There are many options concerning the format of Gerber, but i do not know which you have to choose for pcbway. I have no experience with PCB-manufacturers but many others do have. There is a Kicad-forum and from what I gathered it also discusses options and problems related to pcbway. Could you first take a look there? Let me know if you get stuck.

**Comment by danededane** [comment]
Hi again  @gjkrediet , I'm in the middle of building the controller now. The PCB's i received seems fine but i cannot tell if they work yet. So far the only problem i've come across is this:

![image](https://github.com/gjkrediet/Fluid-controller/assets/9024493/36fabed5-13ff-4c46-b6ad-5d730ec37835)

as you can see i've melted the standoff with my soldering iron to get room for the esp.
but it works now.

What doesnt work and are driving me crazy is when i try to verify and compile:

```
Arduino: 1.8.19 (Windows 10), Board: "TTGO T7 V1.4 Mini32, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None, Disabled"

C:\Users\user\Downloads\Fluid-controller-main (1)\Fluid-controller-main\arduino\PendantV2_45\PendantV2_45.ino: In function 'void setup()':

PendantV2_45:171:17: error: 'TFT_BL' was not declared in this scope

   ledcAttachPin(TFT_BL, 0); // TFT_BL, 0 - 15

                 ^~~~~~

C:\Users\user\Downloads\Fluid-controller-main (1)\Fluid-controller-main\arduino\PendantV2_45\PendantV2_45.ino:171:17: note: suggested alternative: 'TFT_BLUE'

   ledcAttachPin(TFT_BL, 0); // TFT_BL, 0 - 15

                 ^~~~~~

                 TFT_BLUE

C:\Users\user\Downloads\Fluid-controller-main (1)\Fluid-controller-main\arduino\PendantV2_45\PendantV2_45.ino: In function 'void activeTimer(bool)':

PendantV2_45:1129:20: error: 'TFT_BL' was not declared in this scope

       digitalWrite(TFT_BL, LOW);

                    ^~~~~~

C:\Users\user\Downloads\Fluid-controller-main (1)\Fluid-controller-main\arduino\PendantV2_45\PendantV2_45.ino:1129:20: note: suggested alternative: 'TFT_BLUE'

       digitalWrite(TFT_BL, LOW);

                    ^~~~~~

                    TFT_BLUE

PendantV2_45:1130:24: error: 'TFT_DISPOFF' was not declared in this scope

       tft.writecommand(TFT_DISPOFF);

                        ^~~~~~~~~~~

C:\Users\user\Downloads\Fluid-controller-main (1)\Fluid-controller-main\arduino\PendantV2_45\PendantV2_45.ino:1130:24: note: suggested alternative: 'TFT_INVOFF'

       tft.writecommand(TFT_DISPOFF);

                        ^~~~~~~~~~~

                        TFT_INVOFF

PendantV2_45:1131:24: error: 'TFT_SLPIN' was not declared in this scope

       tft.writecommand(TFT_SLPIN);

                        ^~~~~~~~~

C:\Users\user\Downloads\Fluid-controller-main (1)\Fluid-controller-main\arduino\PendantV2_45\PendantV2_45.ino:1131:24: note: suggested alternative: 'TFT_eSPI'

       tft.writecommand(TFT_SLPIN);

                        ^~~~~~~~~

                        TFT_eSPI

Multiple libraries were found for "WiFi.h"

 Used: C:\Users\user\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\WiFi

 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi

exit status 1

'TFT_BL' was not declared in this scope



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

```

which tft module are you using?

**Comment by gjkrediet** [comment]
Looks quite nice!
I used the lilygo-t like in the description but from what i see in your photo, yours has a slightly bigger area for the antenna.
I think his type of lilygo development-board uses a modified library. I can not recollect (should have kept a log). Instructions can be found here: https://github.com/Xinyuan-LilyGO/TTGO-T-Display . You could perhaps first try to get one of the examples in the library running. Please let me know if that works. If that is indeed the problem I will update the instructions with the link.
Succes and let me know!

**Comment by danededane** [comment]
I dont know what tft_espi I had downloaded but i saw that it was missing the factory test folder mentionen in the link you posted . So I tried to redownload it and now I think I'm one step closer:

```
Arduino: 1.8.19 (Windows 10), Board: "ESP32 Dev Module, Disabled, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, Core 1, Core 1, None, Disabled"

Sketch uses 1572965 bytes (120%) of program storage space. Maximum is 1310720 bytes.

text section exceeds available space in board

Global variables use 62988 bytes (19%) of dynamic memory, leaving 264692 bytes for local variables. Maximum is 327680 bytes.

Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.

Error compiling for board ESP32 Dev Module.



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

```

**Comment by danededane** [comment]
Alright one step closer . Change some settings in arduino regarding flash size.

![IMG_20231122_105754](https://github.com/gjkrediet/Fluid-controller/assets/9024493/7746e264-45aa-43a7-b236-2442e8529888)

So now I have to change the following I guess?

```
const char *ssid = "yourssid";
const char *password = "yourpassword";
```

**Comment by danededane** [comment]
I was hoping I could use the remote with bt connection directly to the fluidnc, but I can see here that:
[You will not see the Bluetooth options while using the WiFi firmware.](http://wiki.fluidnc.com/en/features/wifi_bt)

Will I be able to connect it to my home network and then it can talk to fluidnc that way through? Or do I really have to isolate fluidnc from my home network?

**Comment by danededane** [comment]
I dont seem to get anything in the serial monitor 

![image](https://github.com/gjkrediet/Fluid-controller/assets/9024493/15563d4d-cfd6-43d5-a7ba-becc44d1a4dd)

The only thing i can do to get any response is pressing the joystick , that turns on the screen , but again nothing in the console ?

**Comment by gjkrediet** [comment]
FLuidnc cannot use both bluetooth and wifi. Perhaps there is a way that I do not know of. I use my setup via usb and via bluetooth. 
Maybe it is possible to change the controller-program so that it communicates via wifi/telnet. I remember there was a discussion about it. There might be people on github or discord who can shed a light on this.
But first it would be nice if you got your controller working. You were right to use a different memory-organisation (minimal spiffs). I mentioned that in the descriptions but it is easy to miss.
The ssid/password are only used for uploading via OTA.
When you reset fluidnc via the terminal/usb do you get a message in the output like: "BT started with FluidNC"?

**Comment by danededane** [comment]
Alright so i have to chose between bluetooth which is the only way the controller can talk to fluidnc and WiFi theres the only way that my pc can talk to fluidnc (fluid nc is in my case a laser engraver and later perhaps also a plasma cutter in my garage . None of it i want inside in my office).. so that is going to be a problem . 
Perhaps i should try to dig after who mentioned something with wifi connection. I remember to have read it also at some point. 

So far i do not have seen anything in the console. Can i reset it in any other way than the buttons on the board or the battery ?

**Comment by danededane** [comment]
Found it here https://github.com/AC8L/FluidNC-Pendant

**Comment by danededane** [comment]
Okay i've managed to get it up and running with the wifi firmware. I dont seem to have any working buttons but ill take a look at it later. Thanks for the help so far! 😄

**Comment by gjkrediet** [comment]
That’s great! Good to know there is someone out there who already solved this problem. I will link this it in my readme.

Enjoy your controller!

 

Van: cvjensen ***@***.***> 
Verzonden: donderdag 23 november 2023 11:35
Aan: gjkrediet/Fluid-controller ***@***.***>
CC: Gertjan Krediet ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [gjkrediet/Fluid-controller] Getting started and Choosing the right hardware (Issue #1)

 

Okay i've managed to get it up and running with the wifi firmware. I dont seem to have any working buttons but ill take a look at it later. Thanks for the help so far! 😄

**Comment by gjkrediet** [comment]
Let me know if I can help with the button-problem.

 

Van: cvjensen ***@***.***> 
Verzonden: donderdag 23 november 2023 11:35
Aan: gjkrediet/Fluid-controller ***@***.***>
CC: Gertjan Krediet ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [gjkrediet/Fluid-controller] Getting started and Choosing the right hardware (Issue #1)

 

Okay i've managed to get it up and running with the wifi firmware. I dont seem to have any working buttons but ill take a look at it later. Thanks for the help so far! 😄
